### ISSUE TITLE
'Wind Stack on Dailies' code causes weapon levels to totally stop being bought

### ISSUE THREAD

**Issue by Patashu** [slivermasterz/AutoTrimps#10]
Case 1) When in Wind, even when enemies have more than enough HP to survive being stacked to 200, weapon levels are not being brought. Here's an example in Spire IV, but it also happens in non-Spire Wind. Value of Wind Stack Cutoff seems to make 0 difference. 'Upgrade Weapon Levels' is on. https://pastebin.com/8ah63TiH

Case 2) When in Ice, dagger that was raided for is not upgraded. 'Upgrade Weapon Levels' is on. https://pastebin.com/cNyXEEgF

Case 3) When in Poison, weapon levels are not upgraded...?!? At this point I realized there must be a bug. Sure enough, if I toggle 'Buy Weapon Levels' off and on, suddenly weapon levels are being brought!  https://pastebin.com/1bJttvUp

Also, there's a bug in the console:

import-export.js:378 Uncaught TypeError: Cannot read property '$worldGrid' of undefined
    at compareModuleVars (import-export.js:378)
    at guiLoop (AutoTrimps2.js:253)

Expected behaviour:

1) In Wind, weapon levels are brought whenever enemies are surviving to 200 wind stack with HP to spare, and weapon level buying stops when enemies survive exactly to 200 wind stack again. I understand this can't be done automatically ATM with current AT infrastructure, which is why 'Wind Stack Cutoff' field exists to do this automatically. But value of said field is ignored and weapons are erroneously never upgraded, so something is badly bugged here.
2) In Ice and Poison, weapon levels should be upgraded as normal, since we don't need to wind stack right now. (EDIT: Or maybe pretend we're doing windstacking in poison, since if we buy too much in poison, it's too hard to wind stack Wind, though 3) below would help. But ice definitely should upgrade as much as possible, we want to get it over with.)
3) Also, maybe stances can be used to help windstack. Quick way to cut damage up to 1/8.

---

EDIT: Another bug: It swaps to 'H' stance when doing 'max map bonus after zone' in wind. But it realizes its mistake after clearing the map once. https://pastebin.com/KQQHQstr

Also, every time the current groups of Trimps dies and it starts heading to maps to 'Max Map Bonus After Zone' the 'how many buildings to build/trimps to hire' counter gets changed to +25, no matter where it was. Another weird bug.

---

EDIT 2: You suggested Auto-Stance 3 to fix the problem. But it has a different bug. It now uses Scrying stance when maxing map bonus! https://pastebin.com/WiVf955t Scrying stance makes sense when bad guys are dying in one hit to get a little extra loot, but makes 0 sense when it's late in the run and they are not dying in one hit anymore.

**Comment by slivermasterz** [comment]
Was not using proper stance for Windstacking. Case Closed.
