### ISSUE TITLE
Sliverz AT makes infinite z525 maps and softlocks

### ISSUE THREAD

**Issue by Patashu** [slivermasterz/AutoTrimps#11]
https://pastebin.com/1QAXjkQN

Using these settings, import the file, then let AT try to run. It'll continually try to make a map, but it's stuck in the middle of the current map.

Toggle Automaps once. It'll finish the map it's running, then make a z525 map every tick and never try to do anything else ever again.

I found the solution is to turn off AT, manually run the z525 map until prestige/max map bonus is done, then turn AT back on. It will go back to the world, go to the end of z525 world and then run void maps as expected.

**Comment by slivermasterz** [comment]
Just tried your save. I get no errors

**Comment by Patashu** [comment]
![image](https://user-images.githubusercontent.com/666597/42482814-1792afec-842d-11e8-8bd1-e3f6fb9b6e05.png)
This is what it looks like. I opened a trimps tab, let AT boot up, then imported the save file in the pastebin.

The problem is that:

1) Auto Maps wants to run the currently selected map to finish it, and successfully does so, displaying the map just before we start fighting in the first cell:

```
runMap (main.js?10:7356)
autoMap (maps.js:770)
mainLoop (AutoTrimps2.js:221)

-->

mapsSwitch(true);
```

But immediately after that, raiding() runs:

```
prestigeRaiding (raiding.js:44)
raiding (raiding.js:32)
mainLoop (AutoTrimps2.js:222)

-->

function prestigeRaiding(setMap) {
    if (game.global.world === mapAtZone) {
        if (getPageSetting('AutoMaps') === 1 && !prestiged) {
            game.options.menu.mapAtZone.enabled = 0;
            autoTrimpSettings["AutoMaps"].value = 0;
            if (!game.global.switchToMaps && game.options.menu.alwaysAbandon.enabled === 0) {
                mapsClicked();
            }
            mapsClicked();
            game.options.menu.repeatUntil.enabled = 2;
            game.global.repeatMap = true;
        }
```

The second mapsClicked(); call kicks us out of the map before we even start fighting in it. Additionally, autoMaps is turned off. Presumably this code exists so that we can immediately begin Raiding (which only works properly if autoMaps is turned off).

However, before autoMaps can stay off, it is immediately turned on again:

```
userscripts (AutoTrimps2.js:287)
mainLoop (AutoTrimps2.js:242)

function userscripts()
{
    //Misc Features
    if (game.global.world === autoTrimpSettings["VoidMaps"].value && game.global.lastClearedCell >= 80 && getPageSetting('AutoMaps') === 0){
        toggleAutoMaps();
    }
```

This completes the bug. Every frame AutoMaps starts prestiging, Raiding stops prestiging and turns off automaps, and the void maps check turns on automaps. With the three different functions always running in the same order forever, we never get anything done unless we manually break the loop.

**Comment by slivermasterz** [comment]
With the settings you gave me, it successfully finished prestiging and then does voids. I'll try again when I get home.

**Comment by Patashu** [comment]
If it still doesn't happen, maybe check which one of the 3 stack traces doesn't happen and why (what condition is different)?
