### ISSUE TITLE
Wrong link in readme.md

### ISSUE THREAD

**Issue by R3dVenom** [slivermasterz/AutoTrimps#12]
In the Readme.md at the install instructions for Firefox users is the script from "NotThat" linked.

> FireFox/GreaseMonkey instructions:

>    GreaseMonkey identifies userscripts by visiting a URL that ends with ".user.js" in them:
>    Visit this URL, and Agree to install the userscript: https://github.com/NotThat/AutoTrimps/raw/gh-pages/.user.js

**Comment by slivermasterz** [comment]
Good catch. Thanks for the report
